---
title: "Regional and Urban Economics"
subtitle: Dental industry
author: "Sindre Halvorsen Øveraas , Sebastian Mena Fløysand, Alen Colakovic & Mona Lisa Jones"
format:
 pdf:
  fontsize: "10"
  documentclass: article
  margin-left: 2cm
  margin-right: 2cm
papersize: A4
editor: visual
bibliography: [references.bib, Mena.bib, Mona_Retail_Agglomeration.bib]
---

## Abstract

## Introduction

Our main task in this assignment is to perform an analysis of geospatial determinants of firm activity.
More specifically we are to focus on the Norwegian dental industry in this regard, and see how geospatial determinants such as distances to shopping malls and CBDs (Central Business Districts), as well as population density can determine dental businesses income and general financial operations.
As an example, central questions in this assignment will be; "Is it more beneficial to be highly centralized in urban areas with high population density and many competitors, or is it a greater advantage to be less centralized to the advantage that the nearest competing company is considerably further away?", "Which determinants appear to be most significant for economic benefit?"

**Hypothesis**

The location choice of firms providing service to end consumers, significantly determine their ultimate growth potential.

**Research question**

What is the most profitable location for dental practice?

## Theoretical Framework

Location theory gives regional economics its scientific disciplinary identity and constitutes its theoretical methodological core @capello2011.
It has typically microeconomic foundation and uses theoretical models as well as adopting a statistical and geographical approach @capello2011.
Furthermore, the theory uses the concept of externalities as disparities in the spatial distribution of activities, thereby laying the territorial bases for dynamic approaches @capello2011.

Regional growth theory involves spatial aspects of economic growth and territorial distribution of income @capello2011.
It also involves generating geographical advantages, in terms of easy or difficult access of a particular area @capello2011.

Keynesian economics also emphasizes the importance of consumer demand in driving economic growth.
In regional economics, this may involve policies that involve consumer spending, such as incentives for buying local products or supporting small businesses or in this case preventing the the death of down town due to competition from shopping malls.
Subsequently, By increasing consumer demand, supporting business in a specific region and promoting economic growth or preventing economic decline @capello2016.

Harald Hotelling's locational equilibrium is determined by a logic of profit maximization whereby each producer controls its own market area.
Productivity advantages of cities and urban clusters with a high density of firms increase profit by attracting a larger number of potential customers, and more productive workers @capello2011.
Furthermore, the attractiveness of a central location increase the cost of rent.

Alonso's bid rent model indicates the most profitable location for firms.
Closer to the centre with agglomeration attributes or in rural areas with spacial monopoly and low rent.
In gravitational models, the attractiveness of the retail location, represent the size of the retail centre.
Furthermore, it depends on the variety of goods which can be purchased at the same location @mccann2013.

The model of potential has the capacity to measure the potential of attractiveness to a place.
Subsequently, the gravitational force is higher in bigger cities or more heavily populated areas.
Furthermore, predicting places of future growth potential for firms, shopping malls or public service more specifically dentist practice @capello2015.

**Interdependent location choice, the Hotelling's model (1929)**

The model assume that given the location of producers, and given demand uniformly distributed geographically (in linear or circular form) the market is divided into areas within each of which there operates a single firm in a duopoly environment.
Furthermore, no relocation costs and demand only depend on location choice @capello2015.

The location game starts off with the total market of AB, firm A in the middle of location A and firm B starts in the middle of location B.
One firm starts relocating closer to the other to take some of the customers in the other market area @capello2015.
The other respond by doing the same and the game continues until both end up in the middle of the market on the broader of AB.
The end of the game is the position where neither can increase sales volume by moving position @capello2015.

A simple explanation of why two dentists providing the same service, at the same price might locate next to each other.
Nevertheless, despite increasing the transportation cost for patients.
Perhaps the simplest way to explain why there is a natural tendency for retailers to cluster in space; a tendency which may help explain the existence of larger agglomerations.

**Marshall's agglomeration principles**

Marshall (1920) broadly divides externalities within agglomeration in three main categories with potential to drive sales.
Firstly, knowledge spill over within industries or product specific technological knowledge.
Furthermore, market transactions in terms of value chain transactions with industry-specialized buyers and suppliers.
Lastly, competition for specialized production factors such as labour and product market competition @nielsen2021Nielsen.

There are solidly established conclusions regarding the excitanse of agglomeration economies @puga2010Puga.
However, less proof of their estimated magnitude therefore identifying the causes of agglomeration economies is proving more difficult @puga2010Puga.
Nevertheless, there is a large theoretical literature that develops these mechanisms @puga2010Puga.
@duranton2004Duranton discuss these classifications and identify learning, sharing and matching as the main causes of agglomeration economies.

A larger market allows for a more efficient sharing of local infrastructure and facilities, a variety of intermediate input suppliers, or a pool of workers with similar skills @puga2010Puga.
Despite higher rent the dental industry and shopping malls, seams to reap higher benefits in more populated areas as they are dependent on being located where there is a higher volume of patients to drive sales.
The attraction for the consumers and users of public facilities is overall cost reduction @puga2010Puga.
Hence, the larger the population sharing facilities the lower the cost per user @puga2010Puga.
Presumably, industrial factories and business clusters are more dependent on being close to raw materials and industrial action.

Furthermore, a larger market also allows for a better matching between employers and employees, improved chances of finding suitable and better quality of matches @puga2010Puga.
Shopping malls require skilled workers to drive sales.
However, they are not so dependent on highly educated workers as dentists whom according to resent study, tend to prefer bigger cities (as they are highly educated) @davis2020Davis.
More-so, cites provide a constant market for specialized skills and more productive work force @puga2010Puga.
Perhaps, a possibility for higher wages being compensated by more efficient workers in bigger agglomeration economies.
That said the Norwegian cities might differ from the american cites in the study, as the population and clusters are no where near the same size.
Lastly, a larger market can also facilitate learning by promoting the development and widespread adaptation of new technologies and business practice @puga2010Puga.

*"Interactions with experienced workers helps acquire valuable skills and experienced workers remain in cities to share the rent of this learning process. Besides this purposeful transition of knowledge, the information literature on learning in cities has also emphasized the casual and unintended flow of information facilitated by big cities."* @puga2010Puga

**Urban location of dentist; The Alonso model**

The model demonstrate geographical locations tied up to location.
It is an urbanized formulation of the nineteenth century von Thünen model @capello2015.
Moreover, in this case used to get an indicating of where the most profitable location for dental practise might be located.
Alonso assumes the existence of a city that cannot be build instantaneously, and therefore of an effective rent-curve from the city centre to the periphery.
Furthermore, it determines the location for a new firm willing to locate in the city and the profit the firm can obtain, which might be different from the normal or average price competition @capello2015.
As the Von Thünen assume a uniformed space where all land is equally fertile, this model envisages a city, endowed with infrastructure which cover the entire city in all directions whereas unit transport costs are constant in space.
More-so, the town or city has a single city centre, and the city centre of business district (CBD) is generally defined as the most attractive for all firms.
@capello2015.
The model also assume perfect competition and unlimited demand, in other words it is supply-orientated @capello2015.
Furthermore, demonstrating a specific production function with fixed coefficients and constant returns to scale.Rent obtained in the model is the remainder left after transport, production costs and profit has been subtracted from revenues @capello2015.
The bid-rent curve will in this case demonstrate the prise of rent within Bank and Financial locations, Retail locations, and industrial locations.

The illustration shows three categories: The most expensive rent closest to the centre is the Bank and finance district, followed by the retail agglomeration areas and industrial sites furthest away from the central point.
Dental practices are service orientated thus depending on population density and central activities.
Opening hours are relay outside of office hours.
Production cost does not appear to be important in this case since dentist is a public service.
Hence, not dependent of regular transportation of sales goods.
The rent realized by the landowner is the envelope of the three rent supply curves @capello2015.
From a Marshallian way of thinking dentists should cluster somewhere in this pink area to reap maximum sales volume.
Other than locating in the inner circle dentists may also increase their profits further out in to other retail agglomeration area.
The attractiveness might be high in these places due to economies of scope.
As the positive benefits from the Marshallian agglomeration attributes play out.
Subsequently, increasing profit by trading higher transportation cost for lower rent.
In addition fewer dentists to compete with.
The attendances to break out of the clusters support Hotelling's game theory of spatial competition which suggests that the spatial monopoly power provides an incentive for firms to use location as a competitive weapon to achieve spatial monopoly @mccann2013McCann.

**Gravitational models**

The centre attracts firms, people and activities.
Furthermore, it influence the central points in diverse ways such as commuter movements, diffusion of knowledge, corporations and network and personal relationship @capello2015.
More-so, they are generated by the intensity of the flows generated between places @capello2015.
The gravitational pull to a place of interest for a dentist will determine how much sales can be generated by locating there.
Several locations can then be measures against each other to determine profit maximisation.
These models has the potential to measures the future attractiveness of a place.
Changes in infrastructure such as easier access to a place might change the attractiveness of a place or move the flow of people.
An example of this could be Rogfast, improving the connection between Haugalandet and Stavanger.
Subserviently, increasing the gravitationally pull between the two places.
Furthermore, The model uses population and distance to measure the attractiveness and relations between two places @capello2015.
Rogfast might move the population of Haugesund further south and a new town centre might occur competing with other retail clusters in years to come.
On the other hand, the flow of people towards Raglamyr might increase until the potential new centre place has grown.
These models have predictive capacity and can be used to estimate the potential impact.
In particular, location of new productive activity in an area @capello2015.
For instance predict where to build a shopping centre @capello2015.
A new shopping centre further south in Haugaland or expansion of excising retail agglomeration areas might be of interest.
As a result of increased population.
By taking these factors in to account dentist could predict the most profitable locations in years to come by predicting the amount of people that will move from one city to another or tow different points of interest within a city.

**Retail Agglomeration and Economies of Shopping Centres**

Town and cities have long had shopping districts in which stores are concentrated.
To some extent such centre points were the result of uncoordinated store-location decisions @brueckner2011.
Nevertheless, not coincidentally according to Hotelling's theory (1929).
He describes the concentration of retail stores by a market desire to create a Nash equilibrium.
At this point all retailers expected sales maximisation outcome cannot be improved by changing position.
Contradictory to the assumption that consumers will shop at the nearest retailer, they are willing to travel significantly further to reach certain central places.
Marshall (1920) points out another explanation for this in his seminal work on agglomeration.
That being,intra-industry knowledge spillovers as mechanisms leading to formation of industry cluster @nielsen2021.
In this case the dental industry information spillovers are bounded in geographical space.
Hence, the need to locate in close proximity.
That being the latest equipment, in order to work faster or the right personnel to attract more patients.
Another way to drive sales in this area could be by dentist specialisation and patients referrals between dentists.

Another important externalities expressed in Marshall (1920) theory is market transactions.
Whereas, geographical proximity reduces transaction cost through several mechanism @nielsen2021.
The market transactions can be extended to the endogenous location of specialized human capital @nielsen2021.
"It is well known among economists and other social scientists that large cities have disproportionately large shares of highly educated workers, and the trend has been growing in recent decades." Baker (n.d.) Presumably, larger cities would then be more attractive to dentists in terms of cost and quality of specialised labour in smaller towns.
Especially, those trying to achieve spatial monopoly end up loosing profit by overpaying for labour or in worst case scenario not finding enough dentists labour and end up compromising on quality.
In both cases growth potential would be compromised.

Marshal also points out the competition within the geographical location.
Hence, the marketplace and business districts give consumers low search and switching costs @capello2015.
The fact that owners of stores seem to prefer highly concentrated shopping.
More-so, it suggests that the sales volumes outweigh the loss attributed to greater price competition.

**Shopping Malls**

Owners of shopping malls "orchestrate" the process of retail agglomeration that happens naturally in towns and cities @brueckner2011.
Naturally, the same retail agglomeration and Nash equilibrium may occur in shopping malls if not more intensely as the shops are in closer proximity.
Furthermore, the potential for more knowledge spillovers, higher volume of market transaction and more competition.
When retail agglomeration is orchestrated by the owner of a shopping mall, the strength and direction of such externalities are taken into account @brueckner2011.
Much so, because the price of rent is dependent on the overall revenue of a shopping mall.
Hence, the owner of the mall wants to choose the mix of stores and their sizes taking these externalities, attributes and anchor stores attractiveness into account @brueckner2011.
The Norwegian retail market for alcoholic beverages is controlled by the state monopoly.
Anchor-stores such as the Wine-monopoly bring in a higher volume of consumers @lai2013Lai.
For example, shoppers visiting the Wine-monopoly in a mall may also visit a clothing store, and even find it beneficial to use public services at the same time.
Nevertheless, they are limited in numbers and needs government approval.
Each municipality must apply to get the wine monopoly in their area.
One of the factors considered in this process is the death of city centre.
A possible reason for this is so called "predatory malls" which are purposely built to overtake the exciting local market.
Perhaps more so if malls cater for cinema, restaurants, bars and other attributes in conjunction with the city centre.
Not to mention the upper hand of easy road access and free parking.

## Data

`In quantitative studies this section provides details about dataset, variables, instruments and measurement procedures used in the study. If the data was collected by the authors this section will describe how the sample was collected. If specific instruments were constructed to collect the data they will be described here and included in the appendix. Procedures used to measure variables are often described in sufficient detail to permit replication. In economic papers, this section describes the empirical model and estimation strategy used by the authors.`

**Data description**

For this assignment we where provided with different geospatial data in the geographic information software QGIS to calculate the relationship of the different variables that might determine firm activity.
This geospatial data included Norwegian commune data which contained the administrative boundaries of the Communes, presented in the software as different divisions of lines that distinguish the different commune boundaries.
We where also provided with different point layers, such as the geometric centers of communes, urban city centers or Central Business Districts (CBD), all businesses in Norway which are regarded as dental services, and all Norwegian shopping malls.
We where also provided with a QGIS layer with population density estimates, visualized with 100x100 raster graphics.

To carry out a more complete data analysis of the influencing factors of the activity of Norwegian dentist services, we had to collect more data than what we already had been presented with.
We firstly utilized QGIS to calculate different other statistics and variables.
Regarding the Norwegian shopping malls layer we added the variable "Wine-monopoly" as a false/ true variable to determine which Norwegian malls had a hard liquor store.
We added the number of stores which are in each mall, to use as an estimate for the malls sizes.
The malls opening hours have also been included in this layer.
From SSB, we gathered data on the average municipal sales per inhabitant in retailing for each Norwegian commune.
Lastly we created 2 kilometer buffer zones around dentists and CBDs to determine population density in these areas.

After calculations in QGIS we transferred our data to RSTUDIO to do the primary statistical analysis of our data.
The data is then merged into two different data frames.
The first one containing Norwegian communes as the unit of observation, which includes geometric commune centers to the nearest mall, the retail per capita per commune, the different commune numbers and the size of the nearest mall, including the true/ false "Winemonopoly" variable.
The second data frame use dentists as the unit of observations.
This data frame include data on the distances from CBD to dentists, distances from dentists to the nearest mall, including variables of the mall size and the "Winemonopoly" variable, different significant accounting figures for the different dentist businesses, such as total sales revenue and EBIT (Earnings Before Interests and Taxes).

To obtain a first impression and a simple understanding of our data, we have decided to make use of scatterplots.
The scatterplot presented in @fig-1 show the relationship of average spending on retail amongst inhabitants and the distance from geometrical commune centers to nearest malls, which indicate that most malls are in a 50 km radius of commune centers, and that Norwegians on average spend between 50 thousand to 120 thousand on retail.

We furthermore have used plots to look at the relationship between the income of dentist's businesses and the distance from CBDs.
The scatterplot in @fig-2 have some extreme figures of 1 billion+ income which we choose to ignore and deem as outliers, as we notice that these observations are accounting figures for an entire group of companies under the same legal name, and not individual companies.
By ignoring these outliers we are then left with the scatterplot in @fig-3.
This plot shows a tendency of a negative relationship between the variables, which might suggest that dentists might earn more closer to CBDs.
The last scatterplots we have chosen to calculate is concerning the relationship of dentists EBIT which is earnings before interest and taxes, compared to their distances to the nearest shopping mall in @fig-4.
Just as the previous scatterplot, we also see here a tendency of a negative relationship between the variables.
A decent number of dentists run at a loss, having negative earnings before interest and taxes.

## **Econometric Approach**

The questions addressed are related to the geographical space of Norway.
Norway is a country with relatively small population and large heterogeneous land area.
Furthermore, the population is decentralized with the majority of population living in urban areas.
This unique spatial distribution of land might give a possible explanation to diversions from the simple theoretical models used in this paper.
Whereas one of the assumptions are homogeneous landscape.
Nevertheless, the way economies are organised comes partly from the emergence of centralities within a city.
Transportation networks have the potential to increase sprawl depending on how the urban system evolves gradually.

The results from the bid rent configuration from the city centre gave the opportunity to explore other locations in each municipality's.
Having an urban system of multiple centres and applying the same logic of the model to other retail agglomeration areas.
Resulting in finding relationships based on three different types of distance measurements.
Firstly, the distance between Dental Practice and CBD then, dentist and other retail agglomeration areas and lastly amongst dentists.
Finding that most dentist are either located close to a City, Central Business District or a shopping mall.
Additionally, dentist also located close to each other making some sort of industrial cluster.
Supporting, Marshall's agglomeration theory on knowledge spillovers, increasing the sills to attract more patients.

Furthermore, when using the dentist income (y) and comparing the distance from the mall (x), signs of patterns emerge showing that income is greater when the dentist is placed closer to the shopping mall.
Furthermore, decreasing as the distance gets bigger.
Faster transportation can increase convenience of commuting, increasing rent commuters from the city centre are willing to pay, and therefore increasing the area of developed land without this being necessary corresponding to an increase in population.
Hence supporting findings; when the distance reach around 10km from the mall the income starts to increase before it decrease again around 20km.
Also in line with the Keynesian theory suggesting that this pattern might take place as the transportation cost for individuals further away from the Shopping mall does not increase to much by travelling the extra distance.
Hotelling also describes this case where the consumer are willing to travel further to reach a certain central place.

The size of the mall also has a positive effect on revenue for dentist practice, as larger malls tends to have have positive effect on the revenue.
Larger malls gives the customer more options to choose from and are often placed closer to a larger CBD which might be more attractive for customers to visit, and then also explaining why customers could be more interested in traveling further to visit these malls instead of visiting the local mall in a smaller CBD.

More so, the reasoning for a more profitable business close to a shopping malls can be explain by customers beeing able to combine their dentis visit with shopping afterwards, maybe in a way to threat them self.
You can find some similiarities in marketing strategies for grocery stores in the sense where they alwyas have a well planned system of where all their products are.
Where for example gums and grab and go snacks, will always be placed next to the cashier.
these are usually cheap, small and quick to consume, and something that you dont usually look for, but since you are already there, you might aswell.
Same thoughts goes for people who visit the dentists in or fairly close to a mall.
they are already there and might aswell be done with their shopping.
This tradeoff can be highly beneficial for the mall itself, considering the patients going to the dentists then also become customers of the mall by default.

\
According to the Alons's model dentist should locate close to the CBD for higher volume of sales.
Dentist being placed further out in to other retail agglomeration areas can also be a good strategy.
However, the dentist would then rely on the area having less competition so the rate between competition and population density are proportional.
Our findings in QGIS shows that in areas of high population density, the number of dentist also increase.
The consumer/patient then has more to choose between and the dentist also has a bigger scale of potential customers.
Where in smaller areas it is less competition and the dentist would appear to have somewhat of a monopoly since the transportation cost to the second closes dentist are noticeable higher.

Findings suggest that locating further away from a CBD has a positive effect on the revenue for dentist and also that moving further away from the competition has a negative effect on revenue.
These findings could come across as surprising at first, but taking in ti comparison that some of the CBD´s obtained from QGIS could be categorized as relatively small, one explanation to this would possibly be that the data contains a larger number of smaller CBD´s with fewer dentist offices that also has less potential customers and a weaker income which pulls the result in one direction.
The fact that the population density (X_sum) also shows a positive effect on the revenue strengthen this theory.
Areas with a higher population density tends to increase the revenue for dentist.

\
Furthermore, being aware of the fact that going to the dentist is a public services and most people get assigned to their closest dentist based on their living address.
This also takes away some of the competition and would support placement in more rural areas.
More-so, is important to notice that when passed 18 years of age, you could risk loosing your local public dentist due to lack of capacity.
Suggesting some dentist might seek closer to CBD areas to capture most of the remaining part of the population.
Business, public places and industry can have a positive effect on revenue since this is areas where most of the population spends their time during their day, either going to work, school and other errand.
Reducing the transportation cost for the customer as they are already located in these areas even if they do not live here.

The bid rent models are under the assumption that Dentists use spatial completion to maximise profit.
Nevertheless, the cost of dental care in Norway can vary depending on a number of other factors such as the type of treatment, the location of the dental practice and the dentist experience and qualifications.
The Norwegian Dental Association rate the average cost of check ups is between four to eight hundred Norwegian Krone's \@tannlege.
Bertrand model also take price as competitive advantage in to consideration.

Another Mashiallian point to be made could be the advantage of industry clusters.
Taken for granted that the data on Dentist includes both "normal Dentists" and specialist.
Where in this case a "normal dentist" would for example recommend one of their customers to go see a specialist to get braces.
The customer would then probably prefer to go to the closes specialist.
The access to work force in these areas would also be good and will be within the same geographic area.

\
Shopping malls have a relatively short history in Norway, with the first shopping mall opening in the late sixties.
Prior to the most retail activities took place in the city centre.
Furthermore, these malls typically featured a mix of shops, restaurants and entertainment options, and they were often located in suburban areas or on the outskirts of cities \@home-n.
In resent years, there has been a trend towards larger and more comprehensive shopping malls in Norway \@home-n.

However, the growth of shopping malls in Norway has not been without controversy.
Some critics argue that the development of large shopping malls has led to the decline of traditional shopping streets and local businesses, while other raise concerns about the environmental impact of these large scale commercial developments \@kanvin2014.

Information about Wine monopoly locations has also been studied in this paper.
As the wine monopoly are anchor stores they may affect the attractiveness of the shopping mall \@kanvin2014.
The Norwegian government regulates the placements of wine monopoly stores in shopping malls to prevent completion with town centres \@omsorgsdepartementet2022.
More importantly, the government may take in to account the potential impact of exciting retail centres in the region.
This regional economic approach aim to promote sustainable development and balance economic growth across the country \@kanvin2014.

Findings around Wine monopoly shows a negative effect on turnover per capita in retail.
In other words, the Wine monopoly has a bad influence for the turnover in retail.
The explanation could be as mentioned, since Wine monopoly could be categorized as an anchor store, it drag customers from malls and areas where there is no winemonoply over to the areas and malls where a wine monopoly exist, only helping out the stores surrounding.
Another reasoning could be that the winemonopoly drags attention away from the other shopping options, resulting in a negative effect for the turnover for other retailers.

is important to notice that the municipal council is more or less in charge of where Wine monopoly is allowed to operate.
There are several criterias and factors that are taken into consideration before anything gets approved to prevent areas to dry out.
[@kvikstadSeListenDisse2019]

## Conclusion

There are several critical factors that effect the income for dental practice where our result shows that the income tends to be higher located close to a mall or inside the mall itself.
A larger mall also has a positive effect of the income.
Theorys crated by Marshall, Alonso and Keynesian helps us explain some of our findings on why malls shows a pattern to be a better location for dental practice.
However, it is important to notice that a high revenue does not equal good economic results as more populated and central areas tends to have higher fees for example rent.
The Wine monopoly also appears to have negative effect on turnover per capita in retail.

## References

::: {#ref}
:::
